export const env = {
  DATABASE_URL: process.env.DATABASE_URL!,

  REDIS_URL: process.env.REDIS_URL!,
  REDIS_TOKEN: process.env.REDIS_TOKEN!,

  OAUTH_REDIRECT_URL_BASE: process.env.OAUTH_REDIRECT_URL_BASE!,

  DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID!,
  DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET!,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID!,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET!,

  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL!,

  SMTP_SERVER_USERNAME: process.env.SMTP_SERVER_USERNAME!,
  SMTP_SERVER_PASSWORD: process.env.SMTP_SERVER_PASSWORD!,

  JWT_SECRET: process.env.JWT_SECRET!,
};
